:PROPERTIES:
:ID:       e1651e3c-b9d4-4eb8-bffe-4c9996948a65
:END:
#+title: A.I. Chatbots Defeated Doctors at Diagnosing Illness
[[id:56bf58ac-ca7a-4a5e-9591-09474c1ae836][artificial intelligence]]

2024-11-18
* ChatGPT Defeated Doctors at Diagnosing Illness
https://www.nytimes.com/2024/11/17/health/chatgpt-ai-doctors-diagnosis.html
Total annotations: 6

Annotation 1:
Type: Highlight
Quote: "After his initial shock at the results of the new study, Dr. Rodman decided to probe a little deeper into the data and look at the actual logs of messages between the doctors and ChatGPT. The doctors must have seen the chatbot’s diagnoses and reasoning, so why didn’t those using the chatbot do better?It turns out that the doctors often were not persuaded by the chatbot when it pointed out something that was at odds with their diagnoses. Instead, they tended to be wedded to their own idea of the correct diagnosis."
Comment:

Annotation 2:
Type: Highlight
Quote: "In describing how they came up with a diagnosis, doctors would say, “intuition,” or, “based on my experience,” Dr. Lea said."
Comment:

Annotation 3:
Type: Highlight
Quote: "The cases intentionally have never been published so that medical students and others could be tested on them without any foreknowledge. That also meant that ChatGPT could not have been trained on them."
Comment:

Annotation 4:
Type: Highlight
Quote: "The experiment involved 50 doctors, a mix of residents and attending physicians recruited through a few large American hospital systems, and was published last month in the journal JAMA Network Open."
Comment:

Annotation 5:
Type: Highlight
Quote: "The chatbot, from the company OpenAI, scored an average of 90 percent when diagnosing a medical condition from a case report and explaining its reasoning. Doctors randomly assigned to use the chatbot got an average score of 76 percent. Those randomly assigned not to use it had an average score of 74 percent."
Comment:

Annotation 6:
Type: Highlight
Quote: "in a study Dr. Rodman helped design, doctors who were given ChatGPT-4 along with conventional resources did only slightly better than doctors who did not have access to the bot. And, to the researchers’ surprise, ChatGPT alone outperformed the doctors."
Comment:
