:PROPERTIES:
:ID:       6df985df-a803-4047-879c-99c7de36099b
:END:
#+title: catching up to crypto
[[id:eb0fca17-4809-4c48-a947-2d46b8a4f9f9][books-cryptocurrency]]


# 📔 Book: Catching Up to Crypto

**Author**:: Ben Armstrong

---
# 🧾 Description
	A fun and authoritative guide to bitcoin and the future of money In Catching Up to Crypto: Your Guide to Bitcoin and the New Digital Economy, celebrated crypto and Bitcoin expert Ben Armstrong delivers an exciting and fresh new exploration of Bitcoin and digital currencies. He explains what Bitcoin is, how it works, and how and why we're all transitioning to a digital economy as we speak. He discusses the deficiencies of traditional fiat currency, how it's commonly manipulated, and how we can all benefit from the adoption of new, digital assets. In the book, you'll discover how Bitcoin operates in the real-world and how the underlying technology—known as the blockchain—operates. You'll also learn about: The importance of decentralization, trust-less commerce and cryptographic consensus. The humble origins of Bitcoin, as well as how it nearly died out, and how it went on to take over the world How monetary and financial policy is being...

---
# Highlights

- 📚
- Every blockchain starts with one block – the “genesis” block. After a certain amount of time, the programming of the blockchain closes the genesis block (which has a height of zero) and adds another block on top of it – building “height.” As time goes on more and more blocks are stacked on top
-  The structure of a block is set up like this:Block Size: the size of the block (in bytes);Block Header: the information needed to link this block to the chain;Transaction Counter: the count of how many transactions have taken place in this block; andTransactions: the actual transactions recorded in the block (for example, “5BTC from X address to Y address”).Those are the four elements that make up a block on the Bitcoin blockchain
- Broken down into its simplest terms, money is a representation of value, time, effort, and scarcity. Economists usually point to three principles that separate money from other commodities. In order to be classified as money, a commodity must operate as (1) a medium of exchange, (2) a store of value, and (3) a unit of account
- The genesis block was mined in the wake of the financial crisis of 2008, when the massive bailouts given to irresponsible banks were at the forefront of the conversation. Bitcoin was not a direct response to this single event, but the crisis was a perfect example of the systemic problems that Bitcoin was hoping to solve
- in the early emails between Satoshi and Hal Finney, Satoshi described Bitcoin as being “very attractive to the libertarian viewpoint.” Indeed, many Libertarians were attracted to Bitcoin, not only because of its privacy ethos but also because of its sound‐money policy, which seemed to be inspired by the Austrian School of economics,16
- The process of mining is essentially computers validating transactions on a blockchain and checking their work against others on the network in order to achieve consensus. The validation work is done through a cryptographic algorithm that forces the mining machine to match the previous block&#x27;s hash or digital fingerprint by guessing its hash. Once a block is confirmed, the work of validating a new block (a group of transactions on a spreadsheet) is rewarded with tokens specific to the blockchain the computer was working on
- Up until now the consensus mechanism described was what&#x27;s called “proof‐of‐work” (PoW) in action. In PoW, computers compete to solve a math problem; the first to finish is rewarded with tokens for doing so.But there&#x27;s another means of getting consensus on a blockchain that&#x27;s done without all this guesswork and hashing. This is called “proof‐of‐stake” (PoS). First mentioned as an alternative to “proof‐of‐work” (PoW) in the Bitcoin talk forums on July 11, 2011, proof‐of‐stake was seen as a means to scale up Bitcoin faster, reduce transaction costs, and allow for more transparency when voting on proposals to the code.5
- There&#x27;s a saying in crypto that “Code is law.” That means any change to the programming of a blockchain, a crypto wallet, or a smart contract should be regarded as changing a law – in other words, something to be taken seriously and with careful consideration by a democratic body
- As of 2022, over 70% of bitcoin mined used green energy, and mining operations are incentivizing power‐grid improvements and green‐energy alternatives everywhere they pop up
- The counter‐economic strategy also called for direct market competition with government services in hopes of replacing them with free‐market alternatives and rendering them obsolete – an act that is typically seen as illegal, if not treasonous. Examples of this strategy in action could include launching an alternative currency to compete with the Federal Reserve, starting a private security organization to compete with the local police, or developing a mutual‐aid society to compete with government welfare. But in order to work, these alternatives would need to serve their communities better than the government agencies they were intended to replace. Konkin expanded on this strategy in his most famous work, “The New Libertarian Manifesto,” which introduced a philosophy based on counter‐economics called “Agorism.” In addition to advocating for things like tax evasion and black‐market activity, Agorism also called for a radical self‐reliance, which advocated avoiding any dependance on the government and doing everything possible to help others also become less dependent.
- Konkin, on the other hand, felt that there was no hope in creating change through the political system, so he favored a more radical approach. He believed we should all start carefully and strategically breaking laws and challenging government power with our own unregulated businesses. In a research paper titled “The Second Economy and the Destabilization Effect of Its Growth on the State Economy in the Soviet Union: 1965–1989,” economists Vladimir Treml and Michael Alexeev suggested that it was just this sort of counter‐economy that led in part to the fall of the Soviet Union, where smuggling, tax avoidance, and daily acts of civil disobedience had become a way of life in response to all‐encompassing regulations
- his many philosophical posts for Silk Road users, Roberts cited Konkin as an influence and inspiration. In a post explaining his ideological background, Roberts said: “I read everything I could to deepen my understanding of economics and liberty, but it was all intellectual, there was no call to action except to tell the people around me what I had learned and hopefully get them to see the light. That was until I read [J. Neil Schulman&#x27;s] Alongside Night and the works of Samuel Edward Konkin III. At last the missing puzzle piece! All of the sudden it was so clear: every action you take outside the scope of government control strengthens the market and weakens the state
- Ross Ulbricht was no angel. But why did he get a double life sentence without the possibility of parole? (As a point of comparison, Sinaloa Cartel leader Joaquin Guzman – El Chapo – was sentenced in 2019 to life in prison for “conducting a continuing criminal enterprise, including large‐scale narcotics violations and a murder conspiracy, drug‐trafficking conspiracies, unlawful use of a firearm, and a money laundering conspiracy… Trial evidence proved the cartel [engaged in] murder, kidnapping, torture, bribery of officials, and other illegal methods.”14
- Many of Ross&#x27;s supporters don&#x27;t believe these accusations are true, and even Curtis Greene, who was the alleged target of the hit, has spoken out on numerous occasions about how he did not believe that Ulbricht ordered to have him killed.16
- What makes Michael Saylor different from most Bitcoiners or Bitcoin Maxis is that he doesn&#x27;t seem to care about Ethereum and altcoins. Instead he thinks they should be regulated as securities or treated like any other tech company. Instead of hating on altcoins, Saylor is hyper‐focused on the merits of Proof of Work, the fact that Bitcoin is a hard asset, and why the current financial system is a scam
- Vitalik was publicly vocal about how he felt the market was overheated. He was also critical of the excessive culture of greed that had come to define the industry, and threatened to leave crypto if things were going to be that way. In a controversial Twitter post, Buterin wrote we “need to differentiate between getting hundreds of billions of dollars of digital paper wealth sloshing around and actually achieving something meaningful for society.”17
- Smart‐contract platforms allow for the financial layer to be built into the applications themselves as a core part of their infrastructure. There are a few major benefits to this approach. Not only is it more decentralized and secure, but it also opens up new possibilities for features and functionality. With applications building on top of the same financial layer, they can now connect and collaborate in ways that were never possible before. This idea is known as “composability,” and sometimes industry insiders use the phrase “Money Legos” to describe how some financial applications are able to plug into one another and build on top of each other
- DeFi stands for “Decentralized Finance,” a term used to classify the decentralized blockchain applications that provide financial services
- Yield farming is basically locking up or lending out your crypto in exchange for rewards; you&#x27;re farming yields, and the platform benefits from your liquidity, because it allows them to serve their other customers
- In August 2021, an upgrade called EIP‐1559 went live that improved the fee structure on the network while also implementing a burn mechanism, which “burned” a portion of each transaction fee, removing it from circulation forever so as to reduce the rate of inflation. The network was also in the process of switching from a Proof‐of‐Work (PoW) consensus mechanism to a unique Proof‐of‐Stake (PoS) design, which means that miners would no longer be needed to secure the network. Instead, a decentralized network of validating “stakers” could lock up some of their ETHs and secure the network from their home computers
