:PROPERTIES:
:ID:       baf15d1f-e706-4c70-b14f-6584d00bc7b4
:END:
#+title: doing good better
[[id:0b089dce-64df-4066-8bd5-3a401de0b097][books-politics]]


# 📔 Book: Doing Good Better: How Effective Altruism Can Help You Make a Difference

**Author**:: William MacAskill

---
# Highlights

- 📚
- If you earn more than $52,000 per year, then, speaking globally, you are the 1 percent. If you earn at least $28,000—that’s the typical income for working individuals in the United States—you’re in the richest 5 percent of the world’s population
- someone living
- below the US poverty line, earning just $11,000 per year, is still richer than 85 percent of people in the world
- How much greater a benefit would that dollar provide the poor Indian farmer than it would provide for ourselves?
- What’s interesting about this graph is that a doubling of income will always increase reported subjective well-being by the same amount. For someone earning $1,000 per year, a $1,000 pay rise generates the same increase in happiness as a $2,000 pay rise for someone earning $2,000 per year, or an $80,000 pay rise for someone already earning $80,000 per year. And so on
- because, if you’re reading this book, then, like me, you’re probably lucky enough to be earning $16,000 per year or more, putting you in the richest 10 percent of the world’s population. That’s a remarkable situation to be in.
- How many people benefit, and by how much? This is the first key question of effective altruism.
- The idea behind the QALY is that there are two ways you can give a health benefit to someone. First, you can “save someone’s life.” (I use quotes here because “saving” a life, of course, only ever means extending someone’s life.) The second way to benefit someone is to improve the quality of their life during the time they are alive. Migraines don’t kill people, but, as someone who occasionally suffers from them, I know that life is better without them.			The QALY combines these two benefits into one metric, using survey data about the trade-offs people are willing to make in order to assess how bad different sorts of illnesses or disabilities
- If you want, you can come up with your own personal quality weights. Think of an ailment that you have suffered from at some point in your life. Suppose you suffer from back pain, as I sometimes do. You could think to yourself: If 10 represents how good my life is when I’m perfectly healthy, how good is my life on a day when I’m suffering from back pain?
- Economists have used the QALY metric to assess the cost-effectiveness of different health treatments. They test a certain program, assess how much it costs and what health improvements it provides
- If you have limited resources, then, other things being equal, you should spend those resources in whatever way will provide the most QALYs.
- If I were to give to the Fistula Foundation rather than to the charities I thought were most effective, I would be privileging the needs of some people over others merely because I happened to know them
- Those who were infected would be badly disfigured for the rest of their lives, and about 30 percent would die. In the twentieth century alone, smallpox killed more than three hundred million people. Fortunately, in 1977, we eradicated it.			It’s difficult to comprehend just how great an achievement this was, so let’s make a comparison. Suppose we’d achieved world peace in 1973. How many deaths would have been prevented? That timescale includes the killings of Cambodia’s Khmer Rouge, the Rwandan genocide, the two Congo wars, the 9/11 attacks and the wars in Afghanistan and Iraq. If you add up all the wars, genocides, and terrorist acts that occurred since 1973, the death toll is a staggering twelve million. Prior to its eradication, smallpox killed 1.5 to 3 million people every year, so by preventing these deaths for over forty years, its eradication has effectively saved somewhere between 60 and 120 million lives. The eradication of smallpox is one success story from aid, saving five times as many lives as world peace would have done.
- Diminishing returns also provides a powerful argument for focusing your altruistic efforts on people in poor countries rather than those in rich countries.			For example, it costs about $50,000 to train and provide one guide dog for one blind person, something that would significantly improve that person’s quality of life. However, if we could use that $50,000 to completely cure someone of blindness, that would be an even better use of money, since it provides a larger benefit for the same cost. Not only is $50,000 enough to cure one person of blindness in the developing world, it’s enough to cure five hundred people of blindness if spent on surgery to prevent blindness from sufferers of trachoma (a bacterial infection that causes the eyelids to turn inwards, causing the eyelashes to scratch the cornea)
- Cancer treatment receives so much more funding than malaria treatment because malaria is such a cheap problem to solve that rich countries no longer suffer from it. (It was eliminated from the United States in 1951.)
- Saving lives is the most important task a doctor can do—and it’s a task that would be taken care of in the absence of almost any individual doctor we could point to. As stated earlier, there are an estimated 878,194 doctors in the United States. Suppose you become the 878,195th doctor. What’s the difference you make as a result? Well, those 878,194 will have already plucked all the low-hanging fruit in terms of easy ways to save lives, so you, as the 878,195th doctor, will have only hard-to-realize opportunities to improve health. That’s unlikely to include performing heart surgeries and more likely to involve treating minor ailments.
- If an amateur chemist created a pill he claimed would reduce crime, we would never administer it to thousands of children without rigorous testing because it would be dangerous, not to mention illegal, to do so. Yet new social programs like Scared Straight can be rolled out without any good evidence behind them
- Earning to give means exactly what it sounds like: rather than trying to maximize the direct impact you have with your job, you instead try to increase your earnings so you can donate more, improving people’s lives through your giving rather than your day-to-day work
- To calculate the expected monetary value of each bet, you look at all the possible outcomes of that bet. For each outcome, you take the monetary gain or loss and multiply it by the probability of the outcome. In this case, there are two possible outcomes, heads and tails. Each has a 50 percent chance of occurring. The expected monetary value of taking the bet is therefore (50% × +$2) + (50% × –$1) &#x3D; $0.50. The expected monetary value of refusing the bet is zero. Taking the bet has the higher expected value, so you should take the bet
- Thinking explicitly about expected value is important because humans are often terrible at assessing low-probability high-value events. Psychologists have found that people either give too much weight to low-probability events (as, perhaps, when people choose to play the lottery), or they simply ignore them all together
- TOP CHARITIES			GiveDirectly
- In developing countries, sweatshop jobs are the good jobs. The alternatives are typically worse, such as backbreaking, low-paid farm labor, scavenging, or unemployment. The New York Times columnist Nicholas D. Kristof illustrated this well when he presented an interview with Pim Srey Rath, a Cambodian woman who scavenges plastic from dumps in order to sell it as recycling. “I’d love to get a job in a factory,” she said. “At least that work is in the shade. Here is where it’s hot.”
- A clear indicator that sweatshops provide comparatively good jobs is the great demand for them among people in developing countries. Almost all workers in sweatshops chose to work there, and some go to great lengths to do so.
- In the early twenty-first century, nearly four million people from Laos, Cambodia, and Burma immigrated to Thailand to take sweatshop jobs, and many Bolivians risk deportation by illegally entering Brazil in order to work in sweatshops there.
- Nobel laureate and left-wing economist Paul Krugman has stated, “The overwhelming mainstream view among economists is that the growth of this kind of employment is tremendous good news for the world’s poor.” Jeffrey Sachs, Columbia University economist and one of the foremost proponents of increased efforts to help those in extreme poverty, has said, “My concern is not that there are too many sweatshops but that there are too few.” The reason there’s such widespread support among economists for sweatshops is that low-wage, labor-intensive manufacturing is a stepping-stone that helps an economy based around cash crops develop into an industrialized, richer society
- when you buy fair-trade, you usually aren’t giving money to the poorest people in the world. Fairtrade standards are difficult to meet, which means that those in the poorest countries typically can’t afford to get Fairtrade certification. For example, the majority of fair-trade coffee production comes from comparatively rich countries like Mexico and Costa Rica, which are ten times richer than the very poorest countries like Ethiopia.
- of the additional money that is spent on fair-trade, only a very small portion ends up in the hands of the farmers who earn that money. Middlemen take the rest. The Fairtrade Foundation does not provide figures on how much of the additional price reaches coffee produces, but independent researchers have provided some estimates. Dr. Peter Griffiths, an economic consultant for the World Bank, worked out that for one British café chain, less than 1 percent of the additional price of their fair-trade coffee reached coffee exporters in poor countries. Finnish professors Joni Valkila, Pertti Haparanda, and Niina Niemi found out that, of fair-trade coffee sold in Finland, only 11 percent of the additional price reached the coffee-producing countries. Professor Bernard Kilian and colleagues from INCAE Business School found that, in the United States, while fair-trade coffee would sell for five dollars per pound more than conventional coffee, coffee producers would receive only forty cents per pound, or 8 percent of that increased price.
- Even a review commissioned by the Fairtrade Foundation itself concluded that “there is limited evidence of the impact on workers of participation in Fairtrade.”
- only 10 percent of the carbon footprint of food comes from transportation, whereas 80 percent comes from production, so what type of food you buy is much more important than whether that food is produced locally or internationally. Cutting out red meat and dairy for one day a week achieves a greater reduction in your carbon footprint than buying entirely locally based food. In fact, exactly the same food can sometimes have a higher carbon footprint if it’s locally grown than if it’s imported: one study found that the carbon footprint from locally grown tomatoes in northern Europe was five times as great as the carbon footprint from tomatoes grown in Spain, because the emissions generated by heating and lighting greenhouses dwarfed the emissions generated by transportation
- Bringing these numbers together ($206 to prevent 153 metric tons of CO2) gives our best-guess estimate at $1.34 per metric ton. Even after trying to be conservative in our calculations, this number may still be too optimistic. So, to play extra safe, we could assume a 300 percent margin of error and use a figure of five dollars per metric ton of CO2 emissions prevented.			Using this figure, the average American adult would have to spend $105 per year in order to offset all their carbon emissions. This is significant, but to most people it’s considerably less than it would cost to make large changes in lifestyle, such as not flying. This suggests that the easiest and most effective way to cut down your carbon footprint is simply to donate to Cool Earth.
- havior. According to Animal Charity Evaluators (a research charity I helped to set up), by donating to charities like Mercy For Animals or the Humane League, which distribute leaflets on vegetarianism, it costs about one hundred dollars to convince one person to stop eating meat for one year
- According to Animal Charity Evaluators (a research charity I helped to set up), by donating to charities like Mercy For Animals or the Humane League, which distribute leaflets on vegetarianism, it costs about one hundred dollars to convince one person to stop eating meat for one year. If y
-  most people don’t have passions that fit the world of work. In one study of Canadian college students, it was found that 84 percent of students had passions, and 90 percent of these involved sports, music, and art. But by looking at census data, we can see that only 3 percent of jobs are in the sports, music, and art industries. Even if only half the students followed their passion, the majority would fail to secure a job
- Research shows that the most consistent predictor of job satisfaction is engaging work, which can be broken down into five factors (this is known in psychology as the job characteristics theory):							Independence—To what extent do you have control over how you go about your work?				Sense of completion—To what extent does the job involve completing a whole piece of work so that your contribution to the end product is easily visible, rather than being merely a small part of a much larger product?				Variety—To what extent does the job require you to perform a range of different activities, using different skills and talents?				Feedback from the job—How easy is it to know whether you’re performing well or badly?				Contribution—To what extent does your work “make a difference,” as defined by positive contributions to the well-being of other people?						As well as job satisfaction, each of these factors also correlates with motivation, productivity, and commitment to your employer. Moreover, these factors are similar to those required to develop flow, the pleasurable state of being so immersed in an activity that you’re completely free of distractions and lose track of time, which some psychologists have argued is the key to having genuinely satisfying experiences.			There are other factors that also matter to your job satisfaction, such as whether you get a sense of achievement from the work, how much support you get from your colleagues, and “hygiene” factors, such as not having unfair pay or a very long commute. But again, these factors have little to do with whether the work involves one of your “passions”—you find them in many different jobs.			The evidence therefore suggests that following your passion is a poor way to determine whether a given career path will make
- Research shows that the most consistent predictor of job satisfaction is engaging work, which can be broken down into five factors (this is known in psychology as the job characteristics theory):							Independence—To what extent do you have control over how you go about your work?				Sense of completion—To what extent does the job involve completing a whole piece of work so that your contribution to the end product is easily visible, rather than being merely a small part of a much larger product?				Variety—To what extent does the job require you to perform a range of different activities, using different skills and talents?				Feedback from the job—How easy is it to know whether you’re performing well or badly?				Contribution—To what extent does your work “make a difference,” as defined by positive contributions to the well-being of other people?
- you need to provide substantial value over the person who the charity would have hired instead. If you offer unusual skills or are particularly good at that job compared to others who would have worked there, then you can offer significant additional value
- you can compare causes by assessing them on how well they do on each of the following three dimensions:			First, scale. What’s the magnitude of this problem? How much does it affect lives in the short run and long run?			Second, neglectedness. How many resources are already being dedicated to tackling this problem? How well allocated are the resources that are currently being dedicated to the problem? Is there reason to expect this problem can’t be solved by markets or governments?			Third, tractability. How easy is it to make progress on this problem, and how easy is it to tell if you’re making progress? Do interventions within this cause exist, and how strong is the evidence behind those interventions? Do you expect to be able to discover new promising interventions within this cause?
