:PROPERTIES:
:ID:       4fdb76ef-c849-4ab8-8d4d-ca01fd0dadbb
:END:
#+title: Crypto Crackup
[[id:eb0fca17-4809-4c48-a947-2d46b8a4f9f9][books-cryptocurrency]]
* Highlights
- One of the earliest traits Trabucco would recall about Sam is that he appeared to almost “barely” sleep while at camp, a habit he seems to have maintained into adulthood

- For Bentham, though, it was simpler: If something causes pleasure, it’s good, and if something causes pain, it’s bad

- Sam would later repeat the following sentiment across multiple interviews: “There’s a chicken tortured for five weeks on a factory farm, and you spend half an hour eating it. That was hard for me to justify.”126

- one night at the end of his freshman year, he was eating tofu for dinner and his friend asked, “Hey, Sam, are you vegetarian now?” He said, “Yes,” even though he had eaten a cheeseburger for lunch that day—but he never ate meat again, Sam told the 80,000 Hours podcast.131 “I had to reframe myself in my own mind as someone who didn’t eat meat.” Then it was easy.132

- Though the first EAs met in a modest university basement over humble hummus sandwiches, the group now has perks and $28 million per year in funding, its own offices, a gym, weekly yoga classes, catering, and a nap room (quantitatively speaking, the increased productivity after a ten-minute nap redeems the ten lost minutes

- The internship was designed to train the inexperienced interns in trading strategies and tactics. Interns took classes on coding, machine learning, and even poker, and in mock trading classes they played games that simulated trading options

- If Ellison is indeed the worldoptimization blogger, she spent an inordinate amount of time writing about books she had read—everything from romances to science fiction, to business books, to mystery novels, to biographies. And like Sam, the worldoptimization blogger felt that her parents, for all their intelligence, failed to “take ideas seriously.”

- In order to best serve the altruistic causes that he was so passionate about, Sam would practice a version of a philosophy called “risk neutrality,” a concept that effective altruists built upon in their work.224 Risk neutrality means focusing on the expected gain of an investment after adjusting for risk—even if the risks are high.

- Different definitions of risk neutrality exist in the wild, but the general spirit of Sam’s version of risk neutrality seems to be this: aggressive risk taking is a good thing, and not being aggressive enough about taking risk for the causes you care about is a bad thing—particularly in the context of “earning to give.”2

- To illustrate risk neutrality, consider a hypothetical situation with two investment options: one which involves a guaranteed payoff of $100, while the other involves a gamble, with a 50% chance of a $200 payoff and a 50% chance you receive nothing. In our hypothetical scenario, the risk neutral investor would be indifferent between the two options, as the expected value (EV) in both cases equals $100. 1. EV = 100% probability X $100 = $100 2. EV = (50% probability X $200) + (50% probability X $0) = $100 + 0 = $100 However, a risk-averse investor would introduce the added variable of risk into their decision, thereby unbalancing the alternatives above.

- I think there are really compelling reasons to think that the ‘optimal strategy’ to follow is one that probably fails—but if it doesn’t fail, it’s great. But as [an effective-altruism] community, what that would imply is this weird thing where you almost celebrate cases where someone completely craps out—where things end up nowhere close to what they could have been—because that’s what the majority of well-played strategies should end with. I don’t think that we recognize that enough as [an effective-altruism] community, and I think there are lots of specific instances as well where we don’t incentivize that.368

- It was during a poker game with friends in Shanghai in 2013 that CZ first heard about Bitcoin.434 CZ didn’t know what it was at the time, but once he began to learn about it, he was hooked on the idea.435 According to crypto news outlet Decrypt, Zhao acted swiftly, selling his house for $1 million and investing that money to buy bitcoin for $600 apiece. (At the time of this writing, one bitcoin is selling for approximately $30,000; the price can change dramatically due to high volatility.)436 A few years later, CZ launched his own crypto exchange, Binance, which is now the largest in the world, with multibillion-dollar daily trading volumes.437

- Sam suggested that ignoring Covid altogether would actually have been a better response than the current one. He wrote, “~1% of the population would have lost ~8 years of life, and another ~30% would have lost ~1 week to sickness. That would have averaged to about 30 days per person, which is frankly a fair bit better than 1.5 years of lockdown + massive inflation + also we’re not done yet

- Sam didn’t enjoy them very often. He lived like a “capitalist monk,” we were told again and again by the press.596 The number of journalists and interviewers who exclaimed, He drives a Corolla!!, during this period—as if that proved his virtue—are too numerous to count.597 “You pretty quickly run out of really effective ways to make yourself happier by spending money,” Sam told Bloomberg among other news outlets. “I don’t want a yacht.”598

- Sam was well suited to this kind of role. He loved hectic days with back-to-back meetings, he told The Generalist, noting, “most of life lives in the margins.”619 At this point, Sam was sleeping as little as two hours per night, taking sporadic naps only when he keeled over from exhaustion. Sam said that he had suffered from insomnia since he was a teenager, so his sleeping habits during that time period may not have been entirely unfamiliar to him

- If the company did, in fact, know and present the numbers correctly, the second step was to compare the two sides of the ledger: assets and liabilities. Sam said he believed the most salvageable situation was that in which assets and liabilities were about equal. “For a relatively small potential incineration of money, we can resolve that problem and make them able to continue operating and carry on and not cause contagion or customers losing assets,” he told Levine.877

- Ultimately, Sam agreed with Piper’s characterization that he was “really good at talking about ethics, for someone who kind of saw it all as a game with winners and losers.”1395 Sam replied that he “had to be” because ethics are what “reputations are made of,” even in the corporate world.1396 He called the whole situation a “dumb game we woke westerners play where we say all the right shiboleths [sic] and so everyone likes us.”1397
    * ethics as a game

- Something that struck Tiffany Fong as particularly jarring in her initial conversation with Sam was when she asked him what he would miss most in prison. His answer would puzzle Fong. “Do you mean what things I would miss rationally or viscerally?” Sam asked her. “And I was like, ‘What?’” she said. “He classified them as if they’re completely separate buckets. I don’t think about things that way. He’s very compartmentalized.”1737
