name: Generate static org-roam-ui page
on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Generate org-roam-ui page
        uses: ikoamu/publish-org-roam-ui@main
        with:
          org-roam-db-filename: roam.db
          site-title: dotORG
          default-section-open: false
          deploy-to-pages: true
